name: qmmm-vqe-biosim
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - -r requirements.txt
variables:
  OMP_NUM_THREADS: "1"
  OPENBLAS_NUM_THREADS: "1"
  MKL_NUM_THREADS: "1"
  NUMEXPR_NUM_THREADS: "1"
  PYTHONUNBUFFERED: "1"
